qna/board/urls.py
from django.urls import path, re_path

from .views import (
    QuestionsTemplateView,
    QuestionDetailView,
    QuestionCreateView,
)

app_name = 'board'
urlpatterns = [
    path('questions/', QuestionsTemplateView.as_view(), name='questions'),
    path('question/<int:pk>/', QuestionDetailView.as_view(), name='question'),
    path('question/create/', QuestionCreateView.as_view(), name='question-create'),
]

qna/qna/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls', namespace='board')),
]

qna/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    """
    QnA User Model

    Fields:
    - Default User fields
    - handle
    """

    handle = models.CharField(max_length=100, null=True, blank=True)

qna/board/models.py
from django.db import models

from django.conf import settings


class Question(models.Model):
    """
    Question Model
    """

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    title = models.CharField(max_length=255)
    body = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.title}'


class Answer(models.Model):
    """
    Answer to questions
    """

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    question = models.ForeignKey('board.Question', on_delete=models.CASCADE)

    body = models.TextField()
    best = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.id} as an answer to {self.question}'

qna/board/forms.py
from django import forms

from board.models import Question


class QuestionModelForm(forms.ModelForm):
    """
    Question Model Form
    """

    class Meta:
        model = Question
        fields = ('user', 'title', 'body')

qna/accounts/views.py
from django.shortcuts import render

# Create your views here.

qna/board/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, DetailView

from board.models import Question
from board.forms import QuestionModelForm
from accounts.models import User


class QuestionsTemplateView(TemplateView):
    """
    Renders questions as a list
    """

    template_name = 'board/questions.html'

    def get_context_data(self, *args, **kwargs):
        data = super(QuestionsTemplateView, self).get_context_data(*args, **kwargs)

        data['questions'] = Question.objects.all()
        data['form'] = QuestionModelForm()
        return data


class QuestionDetailView(DetailView):
    """
    Question details
    """

    model = Question


class QuestionCreateView(TemplateView):
    """
    View to ask questions
    """

    template_name = 'board/question_create.html'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data()

        context.update({
            'form': QuestionModelForm(),
        })

        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        context = self.get_context_data()

        post_data = request.POST.copy()
        post_data.update({
            'user': request.user.id
        })

        form = QuestionModelForm(post_data)

        if form.is_valid():
            form.save()
            context.update({
                'success': True,
                'form': QuestionModelForm()
            })
            return render(request, self.template_name, context)

        # Fall here by default if not valid
        context.update({
            'form': form
        })

        return render(request, self.template_name, context)

qna/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>QnA</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">

</head>
<body>
  <header>
    <div class="logo">
      QnA App
    </div>
    <ul class="list-inline linx">
      <li>
        <a href="{% url 'board:questions' %}">Questions</a>
      </li>
      <li>
        <a href="{% url 'board:question-create' %}">Ask a Question</a>
      </li>
    </ul>
  </header>
  <div class="container">
    <div class="row">
      <div class="column">
        {% block content %}{% endblock content %}
      </div>
    </div>
  </div>
</body>
</html>

qna/templates/board/question_create.html
{% extends 'base.html' %}


{% block content %}



  {% if success %}
    <div class="success" style="background: greenyellow;padding:12px;">
      <p>Your question has been submitted</p>
    </div>
  {% endif %}


  {% if errors %}
  <ul>
    <li>
      You got errors!
      <ul>
        {% for error in errors %}
          <li>{{ error }}</li>
        {% endfor %}
      </ul>
    </li>
  </ul>
  {% endif %}

  <div class="error" style="color: pink">
    <ul>
      {% for error in form.duplicate.errors %}
        <li>{{ error }}</li>
      {% endfor %}
    </ul>
  </div>


  <div class="row">
    <div class="column">
      <h2>Ask a Question</h2>
      <form action="" method="POST" novalidate>
        {% csrf_token %}
        <table>
          <tr>
            <td><label for="form.title.id_for_label">Title</label></td>
            <td>
              {{ form.title }}
              <small style="color: red;">
                {% for error in form.title.errors %}
                  {{ error }}
                {% endfor %}
              </small>
            </td>
          </tr>
          <tr>
            <td><label for="form.body.id_for_label">Body</label></td>
            <td>
              {{ form.body }}
              <small style="color: red;">
                {% for error in form.body.errors %}
                {{ error }}
                {% endfor %}
              </small>
            </td>
          </tr>
        </table>

        <button class="button-primary">Submit</button>
      </form>

    </div>
  </div>
{% endblock content %}

qna/templates/board/question_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <style>
    .question .body {
      padding: 8px 12px;
      border-radius: 8px;
      background-color: #dddddd;
    }

    .answer {
      padding: 8px 12px;
      border-radius: 8px;
      background-color: lavender;
    }

    .baest {
      width: 50px;
      height: auto;
    }
  </style>

  <div class="question">
    <h2>{{ question.title }}</h2>
    <small>asked by: {{ question.user }}</small>
    <div class="body">
      {{ question.body }}

    </div>
    <p>Asked at {{ question.created_at|date:"b j, Y" }}</p>
  </div>

  <hr>

  <div class="container answers">
    <h3>Answers</h3>
    <hr>

    {% for answer in question.answer_set.all %}
      <div class="row">
        <div class="two columns">
          <!-- Is Best -->
          {% if answer.best %}
            <img class="baest" src="{% static 'img/best.jpg' %}" alt="best">
          {% endif %}
        </div>
        <div class="ten columns">
          <div class="answer">
            {{ answer.body }}
          </div>

          <p>Answered by: {{ answer.user }}</p>
          <span class="lm">Last Modified: {{ answer.updated_at|date:"b j, Y" }}</span>
          <hr>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock content %}

qna/templates/board/questions.html
{% extends 'base.html' %}

{% block content %}
  <div>
    <div class="question">
      <table class="u-full-width">
        {% for question in questions %}
          <tr>
            <td>
              <h5>0</h5>
              <span>Answers</span>
            </td>
            <td>
              <h4><a href="{% url 'board:question' question.id %}">{{ question.title }}</a></h4>
              <span>{{ question.user }}</span>
            </td>
          </tr>
        {% endfor %}
      </table>
    </div>
  </div>
{% endblock content %}